development:
  adapter: mysql2
  encoding: utf8
  database: storytree
  pool: 5
  username: storytree
  password: story.tree!

test:
  adapter: mysql2
  encoding: utf8
  database: storytree
  pool: 5
  username: storytree
  password: story.tree!

production:
  adapter: mysql2
  encoding: utf8
  database: storytree
  pool: 5
  username: storytree
  password: story.tree!
